#!/usr/bin/env bash
# Made by MEGAT
# check for cmd line arguments

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# assigning paramentals to visible

path_tpo_file=$1
ip=$2
username=$3
path_to_ssh_key="$4"

# disabbling strict host key checking

scp -o "StrictHostKeyChecking=no" -i "PATH_TO_SSH_KEY" "PATH_TO_FILE" ""USERNAME@IP:~/"

# check transfer if is successful

if [ $? -eq 0 ]
then
	echo "FILE WAS TRANSFERD SUCCESSFULLY"
else
	echo "FILE TRANSFER FAILED"
